version: '3.4'

services:
  maria_db:
    image: maria_db
    
  phpmyadmin:
    image: phpmyadmin

  academicyearservice.api:
    image: ${DOCKER_REGISTRY-}academicyearserviceapi
    build:
      context: .
      dockerfile: Services/AcademicYearService/AcademicYearService.API/Dockerfile

  organizationservice.api:
    image: ${DOCKER_REGISTRY-}organizationserviceapi
    build:
      context: .
      dockerfile: Services/OrganizationService/OrganizationService.API/Dockerfile


  subjectservice.api:
    image: ${DOCKER_REGISTRY-}subjectserviceapi
    build:
      context: .
      dockerfile: Services/SubjectService/SubjectService.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile

volumes:
  maria_db_data:

